String:SetTranslated() method and isStringDisplaying() function.
MontyTRC89/TombEngine pull request #1079
Opened 2023-04-21 08:58 UTC by davidmarr

The **string:SetTranslated()** method sets the translated parameter. 
If it is true, this will be the key string for the translation that will be displayed. If it is false, this will be the string that will be displayed.

The **isStringDisplaying()** function checks whether the string is displayed.
It returns the bool true if it is shown, false if it is hidden.

2023-04-21 13:28 UTC, hispidence requested changes

2023-04-21 13:28 UTC, hispidence commented on TombEngine/Scripting/Internal/TEN/Strings/DisplayString/DisplayString.cpp
> +		ScriptReserved_SetTranslated, & DisplayString::SetTranslated
`@tparam` should be `@tparam bool name`, where name is the name of the argument in the documentation, e.g. `@tparam bool shouldTranslate`. At the moment it thinks `if` is the name of the arg

2023-04-21 13:28 UTC, hispidence commented on TombEngine/Scripting/Internal/TEN/Strings/StringsHandler.cpp
> +bool StringsHandler::isStringDisplaying(DisplayString const& str)
Please capitalise the first letter in the function name, and make the function `const` (if possible).

2023-04-23 12:03 UTC, hispidence approved these changes

2023-04-23 13:06 UTC, Kubsy approved these changes

2023-04-23 13:36 UTC, Sezzary approved these changes

2023-04-23 13:45 UTC, merged