Check levels in Gameflow.lua
MontyTRC89/TombEngine pull request #1087
Opened 2023-04-25 21:18 UTC by davidmarr

Check if there is the title and at least one playable level to avoid crashing the game

2023-04-26 21:16 UTC, Kubsy approved these changes

2023-04-26 23:28 UTC, Lwmte requested changes

2023-04-26 23:28 UTC, Lwmte commented on TombEngine/Scripting/Internal/TEN/Flow/FlowHandler.cpp
> +			if (g_GameFlow->GetNumLevels() == 1)
I am not sure TEN should close if there is no levels exist on the script but title does. Technically, this is correct scenario, and "crashing" engine in such scenario more resembles TRNG or original engine behaviour. I'd just throw a warning and allow engine to load and play title level anyway.

2023-04-26 23:28 UTC, Lwmte commented on TombEngine/Game/control/control.cpp
> +	//Check if there is the title in Gameflow.lua
Can you move this code somewhere higher in hierarchy? Lack of any levels in script is a very low-level error, so I suggest moving this to somewhere around `LoadFlowScript`. Proper way of throwing such error would be producing an exception in that function which will feature custom error message. Then TEN will automatically catch it, log it and exit around line 324 in winmain.cpp.

2023-04-27 21:29 UTC, Lwmte approved these changes

2023-04-28 02:42 UTC, Sezzary approved these changes

2023-04-28 07:22 UTC, merged