Cosmetic changes and fix to harpoon bolts and rockets
MontyTRC89/TombEngine pull request #1131
Opened 2023-06-04 07:42 UTC by Kubsy

2023-06-05 09:42 UTC, Lwmte requested changes

2023-06-05 09:42 UTC, Lwmte commented on TombEngine/Game/Lara/lara_one_gun.cpp
> +						FireHarpoon(laraItem, nullptr);
If you add new argument for the function which is mostly always passed as `nullptr`, you can make this argument default in declaration (.h file).

2023-06-05 09:42 UTC, Lwmte commented on TombEngine/Game/Lara/lara_one_gun.cpp
> +	bool isShatterable = true;
This is incorrect. Why do you remove this condition? Harpoon should remain stuck into the room geometry until it shatters by itself after some interval.

2023-06-05 09:42 UTC, Lwmte commented on TombEngine/Objects/TR3/Vehicles/upv.cpp
> +		// FireHarpoon(*laraItem, nullptr);
According to coding conventions, you should not leave randomly commented code lines in the codebase. If you are not sure if your new code is stable, more tests should be made.

2023-06-05 09:42 UTC, Lwmte commented on TombEngine/Objects/TR3/Vehicles/upv.cpp
> +		//auto orient = EulerAngles(UPVItem->Pose.Orientation.x, UPVItem->Pose.Orientation.y, 0);
As above. If this code is obsolete, remove it.

2023-06-05 09:42 UTC, Lwmte commented on TombEngine/Objects/TR3/Vehicles/upv.cpp
> +		//harpoon->ItemFlags[0] = 1;
As above.

2023-06-06 06:13 UTC, Sezzary commented on TombEngine/Game/Lara/lara_one_gun.cpp
> +void FireHarpoon(ItemInfo& laraItem, Pose* pos)
I would recommend using `std::optional<Pose>` here instead of a `Pose*` pointer.

2023-06-13 12:45 UTC, Kubsy commented
Harpoons shatter upon contact with the wall, which is a regression and should be fixed.

2023-06-14 20:34 UTC, Lwmte requested changes
This pull request introduces serious regressions which have to be fixed.

2023-06-14 20:34 UTC, Lwmte commented on TombEngine/Game/Lara/lara_one_gun.cpp
> +	harpoonItem.ItemFlags[0] = (int)ProjectileType::Normal;
Why?! Harpoon projectile type is harpoon!

2023-06-14 20:34 UTC, Lwmte commented on TombEngine/Game/Lara/lara_one_gun.cpp
> -		if (harpoonItem.HitPoints > 0)
Where this code have gone? It shattered harpoon after a time interval when it stucked into room geometry!

2023-06-14 20:39 UTC, Lwmte commented
![Clipboard-1](https://github.com/MontyTRC89/TombEngine/assets/3331699/29191f30-c53c-4549-8810-1c11f2a9109e)

Also horizontal firing angle was not fixed (when you look sideways underwater).

2023-07-16 15:43 UTC, Kubsy commented
UPV harpoon whoot sfx plays even if there’s amy harpoons left

2023-07-16 16:51 UTC, merged