Animation refactors tier 5
MontyTRC89/TombEngine pull request #1178
Opened 2023-08-06 03:21 UTC by Sezzary

5th tier of refactors to the animation system. Tier 4 was skipped because I had to do more than originally planned. Not finished yet, but reviewing can start. Requires a level format change to work.

Main changes:
- Complete removal of `g_Level.Anims` and `g_level.Frames`. Each object contains its own animations and each animation contains its own frames.
- Cleaner system for handling animation commands.
- Simpler animation data handling.

To do:
- Fix weapon weirdness.
- Fix flare weirdness.
- Fix Shiva death.
- Check turnswitch.
- Check end frame checks in lara_basic.cpp, others.

2024-04-28 11:29 UTC, closed without merging

2024-06-30 14:16 UTC, Jakub768 commented
so far, the SWAT_PLUS enemy doesn't work from my test. I shall test everything else later

2024-07-30 17:31 UTC, Stranger1992 commented
Test Package uploaded [here](https://discord.com/channels/1072511394735464498/1117554544776327270/1267897292057346109)

2024-07-30 21:33 UTC, Stranger1992 commented
Objects Tested and confirmed working as expected

- ID_AIRLOCK_SWITCH
- ID_JUMP_SWITCH
- ID_MAPPER
- ID_RAISING_BLOCK1
- - Successfully raises ID_PUSHABLE_OBJECT_CLIMBABLE
- - Can also "ladder" climb up side of block if climbable flag is enabled in Tomb Editor
- ID_RAISING_BLOCK2
- - Successfully raises ID_PUSHABLE_OBJECT_CLIMBABLE
- - Can also "ladder" climb up side of block if climbable flag is enabled in Tomb Editor
- ID_SWITCH_TYPEX
- - ID_SWITCH_TYPEX (OCB 0, Wall Lever)
- - ID_SWITCH_TYPEX (OCB 1, Small Lever)
- - ID_SWITCH_TYPEX (OCB 2, Small Button)
- - ID_SWITCH_TYPEX (OCB 6, Reach in Hole switch)

2024-07-31 20:36 UTC, Adngel commented
Hi there, I did a run through the enemies:

### **Issues I could replicate:**
- Crash when exiting the game. Something to do with savegame hubs.
- Aiming with single arm.
- Charging bull behaviour (it doesn't push Lara forward, and when it hits a wall, it gets stuck in an animation loop).

### **Issues I found:**
- Couldn't run the game in Debug x64, only in Release x64
- Aiming with revolver when Lara is crouched, she aimed to the ground instead of the enemy.
- TR2_Mercenary_autopistol_2 can't use the animations from TR2_Mecernary_autopistol_1 anymore, causing crash when killed.
- TR4_Ninja_1 (the one with white robe) crashes the game while he is chasing Lara with the sword (maybe when he is trying to do an acrobatic jump ¿?).
- TR5_Mafia_1 and TR5_SWAT, got freeze in idle animation, it does not crash the game if killed.
- TR5_Cooker, TR5_Brown_Beast and TR5_Sea_Witch, haven't got death animation, in develop they get frozen, but in this branch, the game crashes if Lara kills them.

### **Issues I could not replicate:**
- Fix civvy behaviour. (I don't know what the issue was).
- Fix silent and invisible baboon crash. (In my level, inv and silent baboons were edited with their own copy o the animations, so they don't use the normal baboons animations like in original).
- Fix SAS guy. (I don't know what the issue was).

2025-11-24 09:38 UTC, MontyTRC89 requested changes

2025-11-24 09:38 UTC, MontyTRC89 commented on TombEngine/Objects/TR1/Entity/tr1_doppelganger.cpp
> +				// TODO: Check.
TODO: check

2025-11-24 09:38 UTC, MontyTRC89 commented on TombEngine/Objects/TR3/Entity/Shiva.cpp
Are you sure that the condition is correct?

2025-11-24 09:38 UTC, MontyTRC89 commented on TombEngine/Objects/TR3/Entity/tr3_claw_mutant.cpp
> +			if (item.Animation.FrameNumber >= endFrameNumber)
Can't we use TestLastFrame here?

2025-11-24 09:38 UTC, MontyTRC89 commented on TombEngine/Objects/TR3/Entity/tr3_tony.cpp
> +			if (item->Animation.FrameNumber >= endFrameNumber)
TestLastFrame?

2025-11-24 09:38 UTC, MontyTRC89 commented on TombEngine/Objects/TR3/Vehicles/minecart.cpp
> +		// TODO: Ckech frames.
Remember to check this

2025-11-24 09:38 UTC, MontyTRC89 commented on TombEngine/Game/Animation/Animation.cpp
> +		return Vector3i(g_Renderer.GetMoveableBonePosition(item.Index, boneID, relOffset.ToVector3()));
```
Vector3i GetJointPosition(const ItemInfo& item, int jointIndex, const Vector3i& relOffset)
{
	bool incorrectJoint = false;
	if (jointIndex < 0 || jointIndex >= Objects[item.ObjectNumber].nmeshes)
	{
		TENLog("Unknown joint ID specified for object " + GetObjectName(item.ObjectNumber), LogLevel::Warning, LogConfig::All);
		incorrectJoint = true;
	}

	// Always return object's root position if it's invisible, because we can't predict its
	// joint position otherwise, since it's not animated.
	if (incorrectJoint || Objects[item.ObjectNumber].Hidden || item.Status == ITEM_INVISIBLE)
		return Geometry::TranslatePoint(item.Pose.Position, item.Pose.Orientation, relOffset);

	// Use matrices done in renderer to transform relative offset.
	return Vector3i(g_Renderer.GetMoveableBonePosition(item.Index, jointIndex, relOffset.ToVector3()));
}
```
this is from master, why we are avoiding those checks there?

2025-11-24 09:38 UTC, MontyTRC89 commented on TombEngine/Game/Animation/Animation.cpp
> +	}
```
Vector3 GetJointOffset(GAME_OBJECT_ID objectID, int jointIndex, bool discardZSign)
{
	const auto& object = Objects[objectID];
	int boneIndex = object.boneIndex + (jointIndex * 4);

	if (g_Level.Bones.size() <= boneIndex)
		return Vector3::Zero;

	int* bonePtr = &g_Level.Bones[boneIndex];
	auto result = Vector3(*(bonePtr + 1), *(bonePtr + 2), *(bonePtr + 3));

	if (discardZSign)
		result.z = abs(result.z);

	return result;
}
```
same here, thos checks are from master, should we add them back?

2025-11-24 09:38 UTC, MontyTRC89 commented on TombEngine/Game/Lara/lara_one_gun.cpp
> +
Why?

2025-11-24 09:38 UTC, MontyTRC89 commented on TombEngine/Game/Lara/lara_one_gun.cpp
> +	player.RightArm.AnimObjectID = GetWeaponObjectID(weaponType);
Why?

2025-11-24 09:38 UTC, MontyTRC89 commented on TombEngine/Game/Lara/lara_overhang.cpp
> +	if (item->Animation.AnimNumber == LA_REACH_TO_MONKEY/* && !GetFrameIndex(item, 0)*/) // Manage proper grabbing of monkey slope on forward jump.
Why have you removed that check?

2025-11-24 09:38 UTC, MontyTRC89 commented on TombEngine/Game/effects/item_fx.cpp
> -
Why removed?

2025-11-24 09:38 UTC, MontyTRC89 commented on TombEngine/Game/effects/item_fx.cpp
> -
Why removed?

2025-11-24 09:38 UTC, MontyTRC89 commented on TombEngine/Game/effects/item_fx.cpp
> -
Why removed?

2025-11-24 09:38 UTC, MontyTRC89 commented on TombEngine/Game/missile.cpp
> +using namespace TEN::Collision::Point;;
Remove double ;

2025-11-24 09:38 UTC, MontyTRC89 commented on TombEngine/Game/savegame.cpp
We'll have problems with old savegames because we remove some fields?

2025-11-24 09:38 UTC, MontyTRC89 commented on TombEngine/Objects/TR4/Entity/tr4_baddy.cpp
> +				if (item->Animation.FrameNumber == GetAnimData(*item).EndFrameNumber)
I have doubts about the -1 factor that was removed

2025-11-24 09:38 UTC, MontyTRC89 commented on TombEngine/Objects/TR4/Object/tr4_element_puzzle.cpp
> +					16 || // TODO: Typo?
Solve this.

2025-11-24 09:38 UTC, MontyTRC89 commented on TombEngine/Objects/TR4/Object/tr4_scales.cpp
> +		if (true/*Objects[item->ObjectNumber].animIndex*/) // TODO: Check. Not clear what the intent is.
Solve this.

2025-11-24 09:38 UTC, MontyTRC89 commented on TombEngine/Objects/TR5/Entity/tr5_roman_statue.cpp
I think that this is wrong. Deltaframe2 seems to be "how many frames before last frame". Please check this.

2025-11-24 09:38 UTC, MontyTRC89 commented on TombEngine/Objects/Utils/object_helper.cpp
> +	const auto& anim = GetAnimData(object, 0); // TODO: Check.
Have you checked?

2025-11-24 09:38 UTC, MontyTRC89 commented on TombEngine/Objects/Utils/object_helper.cpp
> +		const auto& anim = GetAnimData(requiredObject, 0); // TODO: Check.
Have you checked?

2025-11-24 09:43 UTC, Sezzary commented on TombEngine/Game/Lara/lara_overhang.cpp
> +	if (item->Animation.AnimNumber == LA_REACH_TO_MONKEY/* && !GetFrameIndex(item, 0)*/) // Manage proper grabbing of monkey slope on forward jump.
Overhang is broken and needs to be rewritten from scratch. This got in the way so it was commented out.

2025-11-24 09:46 UTC, Sezzary commented on TombEngine/Objects/TR3/Entity/tr3_claw_mutant.cpp
> +			if (item.Animation.FrameNumber >= endFrameNumber)
It could, but it needs to be tested. Might result in an off-by-one error. Many of these end-frame checks were fragile.

2025-11-24 09:47 UTC, Sezzary commented on TombEngine/Objects/TR3/Entity/Shiva.cpp
Yes, this makes the Shiva work correctly.

2025-11-24 09:47 UTC, Sezzary commented on TombEngine/Objects/TR3/Entity/tr3_tony.cpp
> +			if (item->Animation.FrameNumber >= endFrameNumber)
Same as above.

2025-11-24 09:48 UTC, Sezzary commented on TombEngine/Game/Animation/Animation.cpp
> +		return Vector3i(g_Renderer.GetMoveableBonePosition(item.Index, boneID, relOffset.ToVector3()));
Possibly a bad merge.

2025-11-24 09:49 UTC, Sezzary commented on TombEngine/Game/Animation/Animation.cpp
> +	}
I don't know what the `bool` is for, looks like a bad merge.

2025-11-24 09:51 UTC, Sezzary commented on TombEngine/Game/Lara/lara_one_gun.cpp
> +
The legacy weapons subsystem is a hideous mess, so I had to hack my way through. Don't mind any of it. The whole thing needs a rewrite from scratch. :)

2025-11-24 09:51 UTC, Sezzary commented on TombEngine/Game/Lara/lara_one_gun.cpp
> +	player.RightArm.AnimObjectID = GetWeaponObjectID(weaponType);
Same as above.

2025-11-24 09:53 UTC, Sezzary commented on TombEngine/Game/effects/item_fx.cpp
> -
Frames are now relative, so it's unnecessary. The case can be left as a fall-through.

2025-11-24 09:53 UTC, Sezzary commented on TombEngine/Game/effects/item_fx.cpp
> -
Same as above.

2025-11-24 09:55 UTC, Sezzary commented on TombEngine/Game/effects/item_fx.cpp
> -
This was unused and didn't do anything.

2025-11-24 09:55 UTC, Sezzary commented on TombEngine/Game/missile.cpp
> +using namespace TEN::Collision::Point;;
Ok

2025-11-24 09:56 UTC, Sezzary commented on TombEngine/Game/savegame.cpp
Arm animation fields need to be redone, but the rest should be okay.

2025-11-24 09:57 UTC, Sezzary commented on TombEngine/Objects/TR4/Entity/tr4_baddy.cpp
> +				if (item->Animation.FrameNumber == GetAnimData(*item).EndFrameNumber)
IIRC, this fixed an off-by-one error. A test should confirm if behaviour is correct.

2025-11-24 09:57 UTC, Sezzary commented on TombEngine/Objects/TR4/Object/tr4_element_puzzle.cpp
> +					16 || // TODO: Typo?
Looks like a decomp leftover.

2025-11-24 09:58 UTC, Sezzary commented on TombEngine/Objects/TR4/Object/tr4_scales.cpp
> +		if (true/*Objects[item->ObjectNumber].animIndex*/) // TODO: Check. Not clear what the intent is.
I don't know what it does, it's a weird check. The intended behaviour needs to be determined through a test.

2025-11-24 09:59 UTC, Sezzary commented on TombEngine/Objects/TR5/Entity/tr5_roman_statue.cpp
Frames are now relative, so this should be correct.

2025-11-24 10:01 UTC, Sezzary commented on TombEngine/Objects/Utils/object_helper.cpp
> +	const auto& anim = GetAnimData(object, 0); // TODO: Check.
It was a weird check, needs an in-game test to determine intended behaviour.

2025-11-24 10:01 UTC, Sezzary commented on TombEngine/Objects/Utils/object_helper.cpp
> +		const auto& anim = GetAnimData(requiredObject, 0); // TODO: Check.
Same as above.

2025-11-24 10:03 UTC, Sezzary commented on TombEngine/Objects/TR1/Entity/tr1_doppelganger.cpp
> +				// TODO: Check.
Need an in-game test. End frame checks are fragile and prone to off-by-one bugs.

2025-11-25 00:15 UTC, Lwmte reviewed
Generally I recommend to rollback all `SetAnimation(*...` and use an overload. It will make git deltas much cleaner. When (or if) we will fully migrate to references instead of pointers (which is not always preferable), we won't even need to do replacement the second time, because another overload will naturally be used.

Focus on testing:
 - All weapon wielding (animations and anim layering)
 - Flare/torch wielding (make sure that animations are visually correct in all states)
 - Turn switch
 - Skateboard / Skateboard Kid
 - Doppelganger
 - Enemy snowmobile
 - Sophia Leigh
 - Baddy 1/2 sword attacks

2025-11-25 00:15 UTC, Lwmte commented on TombEngine/Game/Animation/Animation.cpp
> +	constexpr auto VERTICAL_VELOCITY_GRAVITY_THRESHOLD = CLICK(0.5f);
I believe this should be in general game constants? Maybe in Constants.h?

2025-11-25 00:15 UTC, Lwmte commented on TombEngine/Game/Animation/Animation.cpp
> +	}
`discardZsign` is used for skinned hair workflow. Original hair workflow had bone offsets in inverted direction, so to maintain compatibility with both legacy and skinned workflow (which assumes hair bone offsets in the same direction as Lara skin), this argument was added to build hair skeleton disregarding bone offset sign.

2025-11-25 00:15 UTC, Lwmte commented on TombEngine/Game/Animation/Animation.cpp
> +			outPose.Orientation.y += (angle >= -rot) ? angle : -rot;
I don't fully understand what's happening here, can you give an example of rotation clamping here?

2025-11-25 00:15 UTC, Lwmte commented on TombEngine/Game/Animation/Animation.cpp
> +	void DrawAnimatingItem(ItemInfo* item)
This function is not used anymore, it can be removed from both cpp and h files.

2025-11-25 00:15 UTC, Lwmte commented on TombEngine/Game/Lara/lara.cpp
> +using namespace TEN::Animation;
Please group `using namespace` entries together.

2025-11-25 00:15 UTC, Lwmte commented on TombEngine/Game/Lara/lara.cpp
> +						SetAnimation(*item, LA_SWANDIVE_DIVE);
Let's provide an overload for `SetAnimation` which accepts pointers and not references. Additionally we can perform a `nullptr` check for such overload, in case pointer was invalidated, or `SetAnimation` was called for an item which was destroyed. Additionally, it will reduce this PR's delta overhead which will make the review process easier.

2025-11-25 00:15 UTC, Lwmte commented on TombEngine/Game/Lara/lara.cpp
> +	AnimateItem(*item);
As above, I think we must have an overload for `AnimateItem` which accepts pointers, not references.

2025-11-25 00:15 UTC, Lwmte commented on TombEngine/Game/Lara/lara_one_gun.cpp
> +	if (item.Animation.TargetState != WEAPON_STATE_UNDRAW && item.Animation.ActiveState != WEAPON_STATE_UNDRAW)
Can we make this code more verbose, like below, starting from line 551?

2025-11-25 00:15 UTC, Lwmte commented on TombEngine/Game/Lara/lara_overhang.cpp
> +	if (item->Animation.AnimNumber == LA_REACH_TO_MONKEY/* && !GetFrameIndex(item, 0)*/) // Manage proper grabbing of monkey slope on forward jump.
Maybe we can just remove this part then?

2025-11-25 00:15 UTC, Lwmte commented on TombEngine/Game/control/control.h
> +namespace TEN::Animation { struct AnimData; }
Why do we need to do forward declaration within namespace block? Just curious.

2025-11-25 00:15 UTC, Lwmte commented on TombEngine/Game/effects/hair.cpp
> +				auto jointOffset = GetJointOffset(ObjectID, i);
Argument must be restored and set to true.

2025-11-25 00:15 UTC, Lwmte commented on TombEngine/Game/effects/hair.cpp
> -					GetJointOffset(ObjectID, (i - 1) - 1, true) :
As above.

2025-11-25 00:15 UTC, Lwmte commented on TombEngine/Game/effects/hair.cpp
> +				segment.Position = GetJointOffset(objectID, 0);
As above.

2025-11-25 00:15 UTC, Lwmte commented on TombEngine/Game/savegame.cpp
Savegames are mostly incompatible between versions, so that's okay. But will this actually cause problems for savegames made while shooting? Just asking.

2025-11-25 00:15 UTC, Lwmte commented on TombEngine/Objects/Generic/Object/burning_torch.cpp
> +		constexpr auto HOLD_ANIM_NUMBER	 = 0;
Maybe we can move this to lara_struct.h and make it an enum?

2025-11-25 00:15 UTC, Lwmte commented on TombEngine/Objects/Generic/Switches/turn_switch.cpp
> +			if ((laraItem->Animation.FrameNumber >= 0 &&
I believe we also need to check if animation is `LA_TURNSWITCH_PUSH_CLOCKWISE_START` here?

2025-11-25 00:15 UTC, Lwmte commented on TombEngine/Objects/Generic/Switches/turn_switch.cpp
> -			if ((laraItem->Animation.FrameNumber >= GetAnimData(*laraItem, LA_TURNSWITCH_PUSH_COUNTER_CLOCKWISE_START).frameBase &&
As above.

2025-11-25 00:15 UTC, Lwmte commented on TombEngine/Objects/TR1/Entity/SkateboardKid.cpp
> -		skateItem.Animation.AnimNumber = Objects[ID_SKATEBOARD].animIndex + (item.Animation.AnimNumber - Objects[ID_SKATEBOARD_KID].animIndex);
I am not sure what exactly is happening here. To me, it looks like that skateboard animation is being synchronized to skateboard kid animation. Needs to be checked asset-side if both objects have similar set of animations.

2025-11-25 00:15 UTC, Lwmte commented on TombEngine/Objects/TR1/Entity/tr1_doppelganger.cpp
> +				item.Pose.Position.y += BLOCK(1 / 16.0f);
Unrelated to this pull request, but I think this must be dehardcoded to actual gravity value.

2025-11-25 00:15 UTC, Lwmte commented on TombEngine/Objects/TR2/Entity/tr2_skidman.cpp
> +			riderItem.Animation.AnimNumber = skidooItem->Animation.AnimNumber;
As with skateboard kid, I think what happens here is animation synchronization. Object needs to be tested.

2025-11-25 00:15 UTC, Lwmte commented on TombEngine/Objects/TR2/Vehicles/skidoo.cpp
> +			SyncVehicleAnim(*skidooItem, *laraItem);
I still don't fully understand the logic of renaming `Animation` to `Anim`. We have a function named `SetAnimation`, and I think it is okay. Can we use full words in function names, please?

2025-11-25 00:15 UTC, Lwmte commented on TombEngine/Objects/TR3/Entity/Shiva.cpp
> +				CreatureKill(item, SHIVA_ANIM_KILL, LEA_SHIVA_DEATH, SHIVA_STATE_KILL, LS_DEATH);
What is `LEA`?

2025-11-25 00:15 UTC, Lwmte commented on TombEngine/Objects/TR3/Entity/Shiva.cpp
> +				item->Animation.FrameNumber -= 1;
Can we use more clear code here? For example, `item->Animation.FrameNumber = GetAnimData(*item).EndFrameNumber` or `item->Animation.FrameNumber = GetFrameCount(item)`?

2025-11-25 00:15 UTC, Lwmte commented on TombEngine/Objects/TR3/Entity/SophiaLeigh.cpp
> +		if ((item.Animation.AnimNumber == SOPHIALEIGH_ANIM_SUMMON_START && item.Animation.FrameNumber > 6) ||
I'd feed this condition to ChatGPT or Claude to check.

2025-11-25 00:15 UTC, Lwmte commented on TombEngine/Objects/TR3/Entity/tr3_claw_mutant.cpp
> +			bright = 28 + 16 - item.Animation.FrameNumber;
Unrelated to this PR, but I'd check tomb3 decompilation to solve this double magic number.

2025-11-25 00:15 UTC, Lwmte commented on TombEngine/Objects/TR3/Entity/tr3_claw_mutant.cpp
> +			if (item.Animation.FrameNumber >= endFrameNumber)
I agree. Let's not functionally change code in this PR, it should only substitute tests with full equivalent.

2025-11-25 00:15 UTC, Lwmte commented on TombEngine/Objects/TR3/Vehicles/minecart.cpp
> +				laraItem->Animation.FrameNumber = 62;
I don't fully understand this - if `laraItem->Animation.FrameNumber == 62` condition was met, then why we do `laraItem->Animation.FrameNumber = 62`? Needs to be checked in tomb3 decompilation.

2025-11-25 00:15 UTC, Lwmte commented on TombEngine/Objects/TR3/Vehicles/minecart.cpp
> +				laraItem->Animation.FrameNumber = 62;
As above.

2025-11-25 00:15 UTC, Lwmte commented on TombEngine/Objects/TR4/Entity/tr4_ahmet.cpp
> +				if (TestLastFrame(*item))
You stated above that `TestLastFrame` can be inconsistent, maybe rollback it to original here too?

2025-11-25 00:15 UTC, Lwmte commented on TombEngine/Objects/TR4/Entity/tr4_ahmet.cpp
> +		if (item->Animation.ActiveState != AHMET_STATE_DEATH || !TestLastFrame(*item))
As above.

2025-11-25 00:15 UTC, Lwmte commented on TombEngine/Objects/TR4/Entity/tr4_baboon.cpp
> +				if (TestLastFrame(*item))
As above.

2025-11-25 00:15 UTC, Lwmte commented on TombEngine/Objects/TR4/Entity/tr4_guide.cpp
> +					item->Animation.FrameNumber == 20)
Are we sure that `GetAnimData(item).frameEnd - 20` equals to `20`? To me, it should be `GetAnimData(item).EndFrameNumber - 20`. Proof in tomb4 code: https://github.com/Trxyebeep/tomb4-legacy/blob/a0620f455350aa4947bbcbe18b417b0368e69fad/TOMB4/game/guide.cpp#L486

2025-11-25 00:15 UTC, Lwmte commented on TombEngine/Objects/TR4/Entity/tr4_horseman.cpp
> +				item->Animation.AnimNumber =HORSEMAN_ANIM_FALL_OFF_HORSE_START;
Add space after `=`, please.

2025-11-25 00:15 UTC, Lwmte commented on TombEngine/Objects/TR4/Entity/tr4_knight_templar.cpp
> +		if (item->Animation.AnimNumber == 0 ||
Please replace `0` with `KTEMPLAR_ANIM_WALK_FORWARD_LEFT_1`.

2025-11-25 00:15 UTC, Lwmte commented on TombEngine/Objects/TR4/Entity/tr4_von_croy.cpp
> +			if (item->Animation.FrameNumber ==  VON_CROY_ANIM_RUN_FORWARD)
Please remove extra space after `==`.

2025-11-25 00:15 UTC, Lwmte commented on TombEngine/Objects/TR4/Entity/tr4_von_croy.cpp
> +					item->Animation.FrameNumber > 45)
It's a typo, also in previous code to this PR. Should be `item->Animation.FrameNumber < 45`. Proof in tomb4 code: https://github.com/Trxyebeep/tomb4-legacy/blob/a0620f455350aa4947bbcbe18b417b0368e69fad/TOMB4/game/voncroy.cpp#L1835

2025-11-25 00:15 UTC, Lwmte commented on TombEngine/Objects/TR4/Object/tr4_element_puzzle.cpp
> +					16 || // TODO: Typo?
Must be `laraItem.Animation.FrameNumber == 16`. Proof in tomb4 code: https://github.com/Trxyebeep/tomb4-legacy/blob/a0620f455350aa4947bbcbe18b417b0368e69fad/TOMB4/game/elements.cpp#L106

2025-11-25 00:15 UTC, Lwmte commented on TombEngine/Objects/TR4/Object/tr4_scales.cpp
> +		if (true/*Objects[item->ObjectNumber].animIndex*/) // TODO: Check. Not clear what the intent is.
Should be `if (item->Animation.AnimNumber == 0)`. Proof in tomb4 code: https://github.com/Trxyebeep/tomb4-legacy/blob/a0620f455350aa4947bbcbe18b417b0368e69fad/TOMB4/game/ahmet.cpp#L165

Additionally, this decompilation seems incorrect. In tomb4, this code block is executed if `if (TestLastFrame(*item))` check succeeded (also check link above for reference).

2025-11-25 00:15 UTC, Lwmte commented on TombEngine/Objects/TR4/Vehicles/motorbike.cpp
> +		SyncVehicleAnim(*motorbikeItem, *laraItem);
Essentially if `SetAnimation` here equals to `SyncVehicleAnimation`, we can use this approach for aforementioned objects which were syncing animations via fuzzy anim index additio (e.g. Skateboard Kid or enemy skidoo).

2025-11-25 00:15 UTC, Lwmte commented on TombEngine/Objects/TR5/Entity/tr5_chef.cpp
> +				if (TestLastFrame(*item))
Please add newline here to split one condition from another. Also I'd use explicit `==` operator check here instead of `TestLastFrame`.

2025-11-25 00:15 UTC, Lwmte commented on TombEngine/Objects/TR5/Entity/tr5_cyborg.cpp
> +					((byte)item.Animation.FrameNumber & 1))
Unrelated to this PR, but it's better to use `(unsigned char)` cast here.

2025-11-25 00:15 UTC, Lwmte commented on TombEngine/Objects/TR5/Entity/tr5_roman_statue.cpp
I agree with Sezz. Splitting into 2 different copies of `deltaFrame` seems redundant here. tomb5 project doesn't do that: https://github.com/Trxyebeep/TOMB5/blob/0aeec3e255a53b48198f571c02995e0471c564cf/TOMB5/game/romangod.cpp#L589

2025-11-25 00:15 UTC, Lwmte commented on TombEngine/Objects/Utils/object_helper.cpp
> +	const auto& anim = GetAnimData(object, 0); // TODO: Check.
You should check if amount of frames is **larger than 1**. Dummy animations always have at least one dummy frame, so this check will now fail.

2025-11-25 00:15 UTC, Lwmte commented on TombEngine/Objects/Utils/object_helper.cpp
> -			object.animIndex = requiredObject.animIndex;
Where actual animation assignment is now placed?

2025-11-25 00:15 UTC, Lwmte commented on TombEngine/Objects/Utils/object_helper.cpp
> +	return true;;
Please remove extra `;`

2025-11-25 00:15 UTC, Lwmte commented on TombEngine/Physics/Objects/CollisionMesh.cpp
> +		return Geometry::GetAabb({ vertex0, vertex1, vertex2 });
I don't fully understand why you are renaming `BoundingBox` to `Aabb` everywhere. First off, it removes clarity. Second, AABB is a very specific terminology which means that bounding box is axis-aligned in 3D space. But abstract bounding box which is _not_ in 3D space can't be axis-aligned, because there's no axis defined for it.

2025-11-25 00:15 UTC, Lwmte commented on TombEngine/Renderer/Renderer.h
> +		void UpdateAnimation(RendererItem* item, RendererObject& obj, const KeyframeInterpData& interpData, int mask, bool useObjectWorldRotation = false);
In my opinion, name of the structure should be `KeyframeInterpolationData`.

2025-11-25 00:15 UTC, Lwmte commented on TombEngine/Renderer/RendererCompatibility.cpp
> -											offset += GetJointOffset((GAME_OBJECT_ID)MoveablesIds[i], b, true);
Please restore the argument and set it to `true`.

2025-11-25 00:15 UTC, Lwmte commented on TombEngine/Renderer/RendererLara.cpp
> -		int baseAnim = Objects[GetWeaponObjectID(weapon)].animIndex;
I'd check if this condition change is correct and if upper body is animated or not animated correctly.

2025-11-25 00:15 UTC, Lwmte commented on TombEngine/Renderer/RendererLara.cpp
> +// MEGA HACK: Arm frames for pistols, uzis, and revolver currently remain absolute.
We can change just to `HACK` here 😆

2025-11-25 00:15 UTC, Lwmte commented on TombEngine/Renderer/RendererLara.cpp
> +			auto interpDataLeft = KeyframeInterpData(leftFrame, leftFrame, 0.0f);
I am not sure why `tempItem` was used here, probably to bypass some Lara animation properties? Flare/torch wielding must be visually checked.

2025-11-25 00:51 UTC, Lwmte commented on TombEngine/Game/Animation/Animation.cpp
> +		return Vector3i(g_Renderer.GetMoveableBonePosition(item.Index, boneID, relOffset.ToVector3()));
Please let's re-add those.

2025-11-25 01:48 UTC, Sezzary commented on TombEngine/Game/Lara/lara.cpp
> +						SetAnimation(*item, LA_SWANDIVE_DIVE);
I can add it, but there needs to be a serious effort to switch over to references wherever possible. While pointers are sometimes needed, they make the codebase crusty. Invalid item checks should be done higher up the call hierarchy.

2025-11-25 01:54 UTC, Sezzary commented on TombEngine/Game/control/control.h
> +namespace TEN::Animation { struct AnimData; }
The fully qualified name is `TEN:::Animation::AnimData`, making it necessary to write the declaration like this.

2025-11-25 01:56 UTC, Sezzary commented on TombEngine/Objects/TR2/Entity/tr2_skidman.cpp
> +			riderItem.Animation.AnimNumber = skidooItem->Animation.AnimNumber;
This is how Lara's animations are synchronised with vehicles, so it should be correct for both the sakeboard kid and skidman. Animations in both slots are exactly aligned.

2025-11-25 02:04 UTC, Sezzary commented on TombEngine/Objects/TR4/Entity/tr4_ahmet.cpp
> +				if (TestLastFrame(*item))
It's not `TestLastFrame` that's inconsistent, but the pre-refactor end-frame checks, which sometimes check for the second-last frame instead of the true last frame. Substituting `TestLastFrame` isn't always an obvious choice, but here it produces correct behaviour.

2025-11-25 02:08 UTC, Sezzary commented on TombEngine/Objects/TR4/Vehicles/motorbike.cpp
> +		SyncVehicleAnim(*motorbikeItem, *laraItem);
Sure, I can make it a generic function.

2025-11-25 02:17 UTC, Sezzary commented on TombEngine/Physics/Objects/CollisionMesh.cpp
> +		return Geometry::GetAabb({ vertex0, vertex1, vertex2 });
I disagree. This creates an AABB, so the naming is clearer, especially since I have OBB function counterparts. It is in fact an axis-aligned bounding box in local 3D space, not an abstract box. Having just "AABB" and "OBB" is much better than the interchangeable `box`, `bbox`, `bounds` we see everywhere as well. I really think the generic name for the DXTK struct was, among many other oddities, a mistake on the library authors' part.

2025-11-25 02:21 UTC, Sezzary commented on TombEngine/Objects/TR2/Vehicles/skidoo.cpp
> +			SyncVehicleAnim(*skidooItem, *laraItem);
The shorter `Anim` is more common, so this was letting it win out. I don't mind either way, but at least this would require less typing?

2025-11-25 02:28 UTC, Sezzary commented on TombEngine/Renderer/Renderer.h
> +		void UpdateAnimation(RendererItem* item, RendererObject& obj, const KeyframeInterpData& interpData, int mask, bool useObjectWorldRotation = false);
Kind of long, but sure. I don't mind coming closer in alignment with TE naming conventions.

2025-11-25 08:00 UTC, Lwmte commented on TombEngine/Game/items.cpp
> +		return BoundingOrientedBox(frameData.Keyframe0.Aabb.Center, frameData.Keyframe0.Aabb.Extents, Pose.Orientation.ToQuaternion());
This return is **incorrect**. It returns local keyframe's bounding box center, not global center. You should add `Pose.Position.ToVector3()` to the first `BoundingOrientedBox` argument.

2025-11-25 08:11 UTC, Lwmte commented
Generally I recommend to rollback all `SetAnimation(*...` and use an overload. It will make git deltas much cleaner. When (or if) we will fully migrate to references instead of pointers (which is not always preferable), we won't even need to do replacement the second time, because another overload will naturally be used.

2025-11-26 07:08 UTC, Sezzary commented on TombEngine/Objects/TR3/Vehicles/minecart.cpp
> +		// TODO: Ckech frames.
Needs in-game test.

2025-11-26 09:57 UTC, Sezzary commented on TombEngine/Game/Animation/Animation.cpp
> +			outPose.Orientation.y += (angle >= -rot) ? angle : -rot;
It's used for AI angles, but I haven't looked into what it does there, just make the code smaller.

2025-11-26 21:32 UTC, Lwmte commented on TombEngine/Game/items.cpp
> +	{
This yields incorrect results compared to `return frameData.Keyframe0.BoundingBox.ToBoundingOrientedBox(Pose)`.

2025-11-26 21:38 UTC, Lwmte commented on TombEngine/Game/items.cpp
> +	return BoundingOrientedBox(
Also yields incorrect results compared to `return (frameData.Keyframe0.BoundingBox + (((frameData.Keyframe1.BoundingBox - frameData.Keyframe0.BoundingBox) * frameData.Alpha))).ToBoundingOrientedBox(Pose)`.

2025-11-26 22:09 UTC, Lwmte commented on TombEngine/Game/savegame.cpp
> +		serializedItem.add_anim_number(itemToSerialize.Animation.AnimNumber);
This causes an exception while saving the game. We are adding the same field twice. I suggest to remove the similar code above (along with `if (Objects.CheckID(itemToSerialize.ObjectNumber, true))` condition).

2025-11-26 22:09 UTC, Lwmte commented on TombEngine/Game/savegame.cpp
>  		if (Objects.CheckID(itemToSerialize.ObjectNumber, true))
This whole condition makes no sense anymore because we don't need to check whether ID exists or not since we are not referencing it while saving anim number.

2025-11-26 22:09 UTC, Lwmte commented on TombEngine/Game/savegame.cpp
> -			item->Animation.AnimNumber = Objects[item->ObjectNumber].animIndex + savedItem->anim_number();
This line also is now meaningless, because we don't have to calculate new index into animation data with the new system. Moreover, I believe this whole block is obsolete, because puzzle hole object swaps to puzzle done on activation. However, I guess it must be left intact for now because we don't know if it will ruin something or not.

2025-11-27 00:42 UTC, Lwmte commented on TombEngine/Game/Animation/Animation.cpp
> +				else
A DOZY mode check is missing here: `if (item.Animation.ActiveState != LS_FLY_CHEAT)`. That's why DOZY mode behaves incorrectly.

2025-11-27 00:44 UTC, Lwmte commented on TombEngine/Game/items.cpp
>  	auto frameData = GetFrameInterpData(*this);
Whole contents of `GetObb()` method can be replaced with this one-liner:

`return GameBoundingBox(this).ToBoundingOrientedBox(Pose);`

This yields correct results, because underlying code is essentially similar to the old code which was removed from this function and replaced with current code which does not correctly work.

2025-11-27 03:00 UTC, Sezzary commented on TombEngine/Game/items.cpp
>  	auto frameData = GetFrameInterpData(*this);
Since `GameBoundingBox` should be on the way out, I wanted to convert here without relying on it. I'll take another look.

2025-11-29 11:04 UTC, Lwmte commented on TombEngine/Game/Lara/lara_helpers.cpp
> -			item->Animation.TargetState = LS_STEP_UP;
Are we sure that manual setting of `TargetState` is not necessary here? `SetStateDispatch` does not set it.

2025-11-29 11:04 UTC, Lwmte commented on TombEngine/Game/Lara/lara_helpers.cpp
> -			item->Animation.TargetState = LS_STEP_DOWN;
As above.

2025-11-29 11:04 UTC, Lwmte commented on TombEngine/Game/Lara/lara_one_gun.cpp
> +	item.Animation.AnimObjectID = item.ObjectNumber;
Why do we need to force `AnimObjectID` here?

2025-11-29 11:04 UTC, Lwmte commented on TombEngine/Objects/TR4/Entity/tr4_baddy.cpp
> +				if (item->Animation.FrameNumber == GetAnimData(*item).EndFrameNumber)
This is present in original code: https://github.com/Trxyebeep/tomb4-legacy/blob/a0620f455350aa4947bbcbe18b417b0368e69fad/TOMB4/game/raghead.cpp#L691

EDIT: After tests and frame-by-frame debugging I found no difference between two versions of the code, so this may stay.

2025-11-29 11:04 UTC, Lwmte commented on TombEngine/Objects/TR4/Object/tr4_scales.cpp
> -	if ((laraItem->Animation.FrameNumber >= GetAnimData(*laraItem, LA_WATERSKIN_POUR_LOW).frameBase + 44 &&
Checks for anim number is also missing here.

2025-11-29 11:04 UTC, Lwmte commented on TombEngine/Objects/TR5/Entity/tr5_hydra.cpp
> +					frame = (item->Animation.FrameNumber / 8) + 1;
I believe this won't work. Original code (https://github.com/Trxyebeep/TOMB5/blob/0aeec3e255a53b48198f571c02995e0471c564cf/TOMB5/game/hydra.cpp#L197) used a bitshift on a negative value to get specific effect pattern. We don't use bitshifts, and we don't have negative values anymore. So the effect needs to be checked.

2025-11-29 11:04 UTC, Lwmte commented on TombEngine/Objects/TR5/Entity/tr5_hydra.cpp
> -			if (!((item->Animation.FrameNumber - GetAnimData(item).frameBase) & 7))
As above. I am not sure that bitwise operation will result in similar output here.

2025-11-29 11:16 UTC, Lwmte commented on TombEngine/Objects/TR1/Entity/tr1_doppelganger.cpp
> +				// TODO: Check.
I agree that something feels strange here. It needs testing.

2025-11-29 11:20 UTC, Sezzary commented on TombEngine/Game/Lara/lara_one_gun.cpp
> +	item.Animation.AnimObjectID = item.ObjectNumber;
This enforces the correct animation slot object just in case.

2025-11-29 11:28 UTC, Sezzary commented on TombEngine/Game/Lara/lara_helpers.cpp
> -			item->Animation.TargetState = LS_STEP_UP;
The new code below means it's no longer required. `GetStateDispatch` checks for `LS_STEP_UP`, and the dispatch occurs according to this result.

2025-11-29 12:39 UTC, Lwmte commented on TombEngine/Objects/TR4/Object/tr4_scales.cpp
> +		(laraItem->Animation.AnimNumber == LA_WATERSKIN_POUR_HIGH && (laraItem->Animation.FrameNumber >= 51 && laraItem->Animation.FrameNumber <= 74)))
Incorrect, it's an issue in develop which was fixed here.

2025-11-29 12:39 UTC, Lwmte commented on TombEngine/Objects/TR4/Trap/tr4_plinthblade.cpp
> +			if (TestLastFrame(item))
I believe it's incorrect.

2025-11-29 12:40 UTC, Lwmte commented on TombEngine/Objects/TR5/Entity/tr5_guard.cpp
> +					else if (TestLastFrame(*item))
To me it looks like this was a mistake in original codebase? Wasn't `frameEnd` absolute?

2025-11-29 12:41 UTC, Lwmte commented on TombEngine/Objects/TR4/Entity/tr4_baddy.cpp
> +				if (item->Animation.FrameNumber == GetAnimData(*item).EndFrameNumber)
Also my concern, needs to be debugged frame by frame

2025-11-29 13:45 UTC, Sezzary commented on TombEngine/Objects/TR4/Object/tr4_element_puzzle.cpp
> +					laraItem->Animation.FrameNumber == 16 ||
Irrelevant, it was a decomp typo.

2025-11-29 22:17 UTC, Lwmte commented on TombEngine/Objects/TR4/Trap/tr4_plinthblade.cpp
> +			if (TestLastFrame(item))
AI glitch.

2025-11-29 22:24 UTC, Lwmte commented on TombEngine/Objects/TR4/Object/tr4_scales.cpp
> +		if (item->Animation.AnimNumber == 0)
Checked, and it is actually correct: https://github.com/Trxyebeep/tomb4-legacy/blob/a0620f455350aa4947bbcbe18b417b0368e69fad/TOMB4/game/ahmet.cpp#L165

2025-11-29 22:24 UTC, Lwmte commented on TombEngine/Objects/TR4/Object/tr4_scales.cpp
> +	if (TestLastFrame(*item))
Fixed

2025-11-30 00:16 UTC, Lwmte commented on TombEngine/Objects/TR4/Entity/tr4_baddy.cpp
> +				if (item->Animation.FrameNumber == GetAnimData(*item).EndFrameNumber)
After tests and frame-by-frame debugging I found no difference between two versions of the code, so this may stay.

2025-12-01 07:53 UTC, Lwmte commented on TombEngine/Game/Animation/Animation.cpp
> +		frameNumber = std::clamp(frameNumber, 0, EndFrameNumber);
This is incorrect and potentially may introduce errors. `EndFrameNumber` does not specify actual last frame in the animation, it only specifies out point where animation should start switching to NextAnim. Actual frame data may be present after EndFrameNumber.

2025-12-13 08:50 UTC, Lwmte commented on TombEngine/Game/Animation/Animation.cpp
> +		frameNumber = std::clamp(frameNumber, 0, EndFrameNumber);
After careful consideration, I think this may stay. TE compiler already clamps `EndFrame` to make sure it never gets out of bounds, plus we may intentionally interpolate only under EndFrameNumber.