Fix spot light attenuation
MontyTRC89/TombEngine pull request #1193
Opened 2023-08-13 18:37 UTC by Kubsy

Branch by Monty

2023-08-14 06:25 UTC, Lwmte requested changes

2023-08-14 06:25 UTC, Lwmte commented on TombEngine/Shaders/DX11_Rooms.fx
> +	//if (input.FogBulbs.w > 0.0f)
Do not comment out lines like that.

2023-08-14 06:25 UTC, Lwmte commented on TombEngine/Shaders/DX11_Rooms.fx
> +	//if (input.FogBulbs.w == 0.0f)
Do not comment out lines like that.

2023-08-23 03:19 UTC, MontyTRC89 commented on TombEngine/Shaders/DX11_Rooms.fx
> +	//if (input.FogBulbs.w > 0.0f)
Done

2023-08-23 03:19 UTC, MontyTRC89 commented on TombEngine/Shaders/DX11_Rooms.fx
> +	//if (input.FogBulbs.w == 0.0f)
Done

2023-08-27 07:05 UTC, merged