Batching for sprites in 2D space
MontyTRC89/TombEngine pull request #1208
Opened 2023-09-07 08:16 UTC by Sezzary

2023-09-08 10:39 UTC, Kubsy approved these changes

2023-09-10 12:34 UTC, Lwmte approved these changes

2023-09-23 10:23 UTC, Lwmte requested changes
Please also rename ALL occurences of `ScreenSprite` to `DisplaySprite`. All 2D space objects must be called `Display...`, not `Screen...`. We already have `DisplayString` and `DisplayPickup`.

2023-09-23 10:23 UTC, Lwmte commented on TombEngine/Game/Lara/lara.cpp
> +	//AddScreenSprite(ID_DEFAULT_SPRITES, 0, Vector2(400, 300), 0, Vector2::One, Vector4::One, 0, BLEND_MODES::BLENDMODE_ALPHABLEND);
I guess this line was here for a test? Please remove it before merging.

2023-09-23 10:23 UTC, Lwmte commented on TombEngine/Game/control/control.cpp
> +		ClearScreenSprites();
Why this call is here? Clearing of screen sprites should happen around cleaning up all other renderer objects, such as strings and particles.

2023-10-06 16:22 UTC, Adngel commented
I tested the beetles swarms, but I got more bugs with this branch. 

Little Beetles have the next OCBs:

0 - 128 = Total number of scarab you want
1000 += Scarab appear from the floor
2000 += Scarab appear from the ceiling
4000 += Scarab slow release followed by a gush

(Use Flipeffect 31 to make them dissapear).

In develop, the game crashes, but beetle spawn animation worked correctly in these 4 ocb states. However in this branch, they do not. When trigger is activated, it takes some seconds for the beetles swarms appear (although they may be reducing Lara's health points from before). When they do appear, they do not perform any of the spawn animations, they just appear the full swarm at the instant.

Also, using the different bettles, I can see that only the first one appears. (I think they may reach the limit) but still there are "invisible" bettles in these cases.

This is a test level I was testing different beetles:
 https://drive.google.com/file/d/1t7iH08BkgUGfEVejGFoMFJB9jFx28cAv/view?usp=sharing 
 (Each one spawn 128 bettles but with different OCB).

2023-10-12 08:46 UTC, merged