Display string scale
MontyTRC89/TombEngine pull request #1224
Opened 2023-09-30 12:54 UTC by hispidence

2023-10-12 17:41 UTC, Lwmte requested changes

2023-10-12 17:41 UTC, Lwmte commented on TombEngine/Renderer/Renderer11Init.cpp
> +	//get all paths in directory matching a pattern
Comments should start with capital letter.

2023-10-15 06:28 UTC, Lwmte approved these changes

2023-10-18 11:36 UTC, Sezzary approved these changes

2023-11-04 15:17 UTC, Adngel commented on Scripts/Engine/Timer.lua
> +local str = TEN.Strings.DisplayString("TIMER", 0, 0, 1, unpausedColor, false, {TEN.Strings.DisplayStringOption.CENTER, TEN.Strings.DisplayStringOption.SHADOW} )
Reminded to fix this line to any of the two options:

Old  format - local str = TEN.Strings.DisplayString("TIMER", 0, 0, unpausedColor, false, {TEN.Strings.DisplayStringOption.CENTER, TEN.Strings.DisplayStringOption.SHADOW} ) 
New format - local str = TEN.Strings.DisplayString("TIMER", Vector2(0,0), 1, unpausedColor, false, {TEN.Strings.DisplayStringOption.CENTER, TEN.Strings.DisplayStringOption.SHADOW} )

2023-11-04 15:44 UTC, Adngel requested changes
I saw nothing out of place and when I tested I hadn't got any issue.

I just going to check a small thing in the Timer.lua and do some last tests before to give my approval.

2023-11-04 16:36 UTC, Adngel approved these changes

2023-11-05 07:02 UTC, merged