Tr1 electric ball
MontyTRC89/TombEngine pull request #1413
Opened 2024-09-26 07:42 UTC by Nemoel-Tomo

## todo

- [**@Kubsy, please  can you help me? ^^** ] I have added a changelog entry to CHANGELOG.md file on the branch/fork (if it is an internal change then it is not needed) 
- [**@Sezz, please can you help me format and simplify?** ] Pull request meets the Coding Conventions standards: https://github.com/MontyTRC89/TombEngine/blob/master/CONTRIBUTING.md#coding-conventions

## Links to issue(s) this pull request concerns (if applicable)
"n/a"

## Description of pull request 

Electric Ball from TR1. it needs 2 Objects.
ID_ELECTRIC_BALL = # 451   (see attachment)
ID_ELECTRIC_BALL_IMPACT_POINT (nullmesh) = # 452

If Lara is out of range, the ball deactivates.
If Lara is within range but not near the ball or is out of sight, it randomly attacks all ID_ELECTRIC_BALL_IMPACT_POINT objects that have the same OCB as the ball itself.

I also changed the appearance of the electric lightning a bit. 
It's just a visual change: to be more precise, a narrower, whiter texture is placed over the main texture. The inside of the bolt is therefore a bit brighter.

[electricBall.zip](https://github.com/user-attachments/files/17144749/electricBall.zip)

2024-10-03 21:30 UTC, TokyoSU requested changes
Nice work, pretty nice effect, some misc change is required through.

2024-10-03 21:30 UTC, TokyoSU commented on TombEngine/Game/effects/Electricity.h
> +		Vector3 armOrigin = Vector3::Zero;;
Double ;;

2024-10-03 21:30 UTC, TokyoSU commented on TombEngine/Objects/Effects/Boss.h
> +		NonPlayerTarget    = (1 << 2)
Why this was changed ?
It make no sense, this enum is only used by TR3 boss.

2024-10-03 21:30 UTC, TokyoSU commented on TombEngine/Objects/TR1/Trap/ElectricBall.cpp
> +			SpawnElectricity(arc.pos4, target.ToVector3() + targetRandom.ToVector3(), 15, 32, 64, 128, 60, (int)ElectricityFlags::Spline | (int)(int)ElectricityFlags::ThinOut | (int)ElectricityFlags::MoveEnd,
Empty comment

2024-10-03 21:30 UTC, TokyoSU commented on TombEngine/Objects/TR1/Trap/ElectricBall.cpp
> +			SpawnElectricity((target.ToVector3() - Vector3(0,220,0)  ) + targetRandom.ToVector3(), target.ToVector3() + targetRandom.ToVector3(), 15, 32, 64, 128, 160,  (int)(int)ElectricityFlags::ThinOut | (
missing space at 0,220,0

2024-10-03 21:30 UTC, TokyoSU commented on TombEngine/Objects/TR1/Trap/ElectricBall.cpp
> +		auto targetPlayer = GameVector(GetJointPosition(LaraItem, LM_TORSO), LaraItem->RoomNumber);;
Double ;;

2024-10-03 21:30 UTC, TokyoSU commented on TombEngine/Objects/TR1/Trap/ElectricBall.cpp
> +		CheckForRequiredObjects(item);
This should only be used for TR3 boss, GetTargetEntityList already do the job.
using CheckForRequiredObjects and changing the enum, you change file is not required in this PR.

2024-10-03 21:30 UTC, TokyoSU commented on TombEngine/Objects/TR1/Trap/ElectricBall.cpp
> +		if (ai.distance < SQUARE(BLOCK(3)) && los)
You could use the OCB as attack range ? OCB 1 = SQUARE(BLOCK(1))
or use OCB for impact point range detection ?

2024-10-03 21:30 UTC, TokyoSU commented on TombEngine/Objects/TR1/Trap/ElectricBall.cpp
> +		if (ai.distance < SQUARE(BLOCK(3)) && los)
Some complained that the range of 3 is too small, OCB should fix it :)

2024-10-03 21:30 UTC, TokyoSU commented on TombEngine/Objects/TR1/Trap/ElectricBall.cpp
> +		if (ai.distance < SQUARE(BLOCK(3)) && los)
Or you can use ItemFlags and make an index a IMPACT detection or LARA range detection range, and can be changed through LUA ?

2024-10-03 21:30 UTC, TokyoSU commented on TombEngine/Objects/TR1/tr1_objects.cpp
> +		obj->SetHitEffect(true);
Should be at the end for consistency.

2024-10-03 21:31 UTC, TokyoSU commented on TombEngine/Objects/TR1/Trap/ElectricBall.cpp
> +			SpawnElectricity((target.ToVector3() - Vector3(0,220,0)  ) + targetRandom.ToVector3(), target.ToVector3() + targetRandom.ToVector3(), 15, 32, 64, 128, 160,  (int)(int)ElectricityFlags::ThinOut | (
Also double (int)(int) cast

2024-10-03 21:37 UTC, TokyoSU commented on TombEngine/Objects/TR1/Trap/ElectricBall.cpp
> +			SpawnElectricity(arc.pos4, target.ToVector3() + targetRandom.ToVector3(), 15, 32, 64, 128, 60, (int)ElectricityFlags::Spline | (int)(int)ElectricityFlags::ThinOut | (int)ElectricityFlags::MoveEnd,
Also double (int)(int) cast

2025-01-08 12:26 UTC, Stranger1992 approved these changes

2025-01-12 16:15 UTC, merged