Add more script examples to Lua API
MontyTRC89/TombEngine pull request #1461
Opened 2024-11-08 18:37 UTC by Jakub768

## Checklist

- [x] I have added a changelog entry to CHANGELOG.md file on the branch/fork (if it is an internal change then it is not needed) 
- [x] Pull request meets the Coding Conventions standards: https://github.com/MontyTRC89/TombEngine/blob/master/CONTRIBUTING.md#coding-conventions

## Links to issue(s) this pull request concerns (if applicable)

n/a

## Description of pull request 

This pull request fills some functions in the API with more (small) example scripts to clarify what they do. There's no need for complex script examples since it will waste space.

2025-01-05 17:50 UTC, Stranger1992 requested changes

2025-01-05 17:50 UTC, Stranger1992 commented on TombEngine/Scripting/Internal/TEN/Objects/Moveable/MoveableObject.cpp
> +// levelFuncs.hasEffect == function()
Is this correct? `levelFuncs.hasEffect == function()` ?

2025-01-05 17:50 UTC, Stranger1992 commented on TombEngine/Scripting/Internal/TEN/Util/Util.cpp
> +	//		if distance < 50.0 then
magic numbers shouldnt be used for example scripts. Please add local variable.

2025-01-05 17:50 UTC, Stranger1992 commented on TombEngine/Scripting/Internal/TEN/Util/Util.cpp
> +	//		if Hdistance < 50.0 then
check spelling here:

hDistance or Hdistance?

2025-01-05 17:50 UTC, Stranger1992 commented on TombEngine/Scripting/Internal/TEN/Logic/LogicHandler.cpp
> +Note: Freeze mode is handled separately so creating stuff in normal game loop then triggering OnFreeze will not work.
avoid using words like "stuff". It isnt very professional. Amend this to "elements" / "functions" and be more specific with what you are trying to say.

2025-01-05 17:50 UTC, Stranger1992 commented on TombEngine/Scripting/Internal/TEN/Logic/LogicHandler.cpp
> +	- instantiate string using DisplayString() and use ShowString(), both in LevelFuncs.OnFreeze function.
Can you provide an example of what you mean here by way of a code snippet.

2025-01-05 17:50 UTC, Stranger1992 commented on TombEngine/Scripting/Internal/TEN/Logic/LogicHandler.cpp
> +@tfield function OnFreeze Will be called when any of the Freeze modes are activated.
un-capitalise Will

2025-01-06 12:36 UTC, Jakub768 commented on TombEngine/Scripting/Internal/TEN/Logic/LogicHandler.cpp
> -@tfield function OnFreeze Will be called when any of the Freeze modes are activated.
The functions you mentioned also have @tfield in them, unless you want me to change them.

2025-01-06 12:37 UTC, Jakub768 commented on TombEngine/Scripting/Internal/TEN/Util/Util.cpp
> +	//		if Hdistance < 50.0 then
hDistance for camelCase. But ultimately doesn't matter. Will rename variable.

2025-01-06 12:42 UTC, Jakub768 commented on TombEngine/Scripting/Internal/TEN/Util/Util.cpp
> +	//		if distance < 50.0 then
there are various cases where magic numbers are used in other examples (not from mine) so I will actually update all of them soon.

2025-01-06 12:42 UTC, Jakub768 commented on TombEngine/Scripting/Internal/TEN/Logic/LogicHandler.cpp
> +Note: Freeze mode is handled separately so creating stuff in normal game loop then triggering OnFreeze will not work.
Fixed.

2025-01-06 12:43 UTC, Jakub768 commented on TombEngine/Scripting/Internal/TEN/Logic/LogicHandler.cpp
> +	- instantiate string using DisplayString() and use ShowString(), both in LevelFuncs.OnFreeze function.
Fixed.

2025-01-06 12:43 UTC, Jakub768 commented on TombEngine/Scripting/Internal/TEN/Logic/LogicHandler.cpp
> +@tfield function OnFreeze Will be called when any of the Freeze modes are activated.
Fixed.

2025-03-08 10:55 UTC, Jakub768 commented
Will remake this PR, moveableObject has been changed completely and it caused some huge frickup.

2025-03-08 10:55 UTC, closed without merging