Math
MontyTRC89/TombEngine pull request #744
Opened 2022-09-18 04:00 UTC by Sezzary

Not complete yet, but maybe at a good state to start reviewing. There are some decisions I am unsure about.

Key changes:
- Organised mathematical functions, objects, and constants within the `Math` folder. It is used like a library; to access, a given file must include `Math/Math.h` in the header. Once namespace issues are sorted out, it will also require using the `TEN::Math` namespace.
- Organised container objects in their own folder, `Math/Containers`.
- Organised function groups with very specific purposes in their own namespaces. Namely, `TEN::Math::Random` and `TEN::Math::Geometry`.
- Replaced `GetLaraJointPosition()` and `GetAbsJointPosition()` functions with the all-purpose `GetJointPosition()`, which returns a `Vector3` object instead of taking an output argument.
- Renamed `PHD_3DPOS` to `PoseData` as the struct is completely different from the original. As previously discussed I am very open to a name other than "pose", but it would need to be something that specifically describes a position+orientation representation.
- Renamed `Vector2Int` to the more common `Vector2i`.
- Renamed `Vector3Int` to the more common `Vector3i`.
- Renamed `Vector3Shrt` to `EulerAngles`. This iteration is an intermediate state of the object of the same name found on the `euler_angles` branch. It adds useful constructors (from direction vector, quaternion, or rotation matrix), converters (to direction vector, quaternion, or rotation matrix).

Please check for my usual deadly typos and help me get things right. :)

2022-09-26 07:32 UTC, rr- commented
IMO each of the bullet should be a separate pull request, now it's a nightmare to review.

2022-10-13 22:21 UTC, asasas9500 requested changes

2022-10-13 22:21 UTC, asasas9500 commented on TombEngine/Math/Containers/BoundingBox.cpp
> +	BOUNDING_BOX::BOUNDING_BOX()
BOUNDING_BOX should be BoundingBox according to coding conventions.

2022-10-14 01:34 UTC, asasas9500 submitted a review, later dismissed

2022-10-24 05:44 UTC, merged