Meshswap refactor
MontyTRC89/TombEngine pull request #828
Opened 2022-11-10 17:21 UTC by Lwmte

Makes both Lara and other objects use same method for assigning meshswaps by directly refering to mesh (bone) index.

This allows to define multiple meshswaps for objects, although because of TEN renderer limitation, you can't assign arbitrary meshes to arbitrary bone indices.

2022-11-10 18:11 UTC, Raildex requested changes
Remove this commit and open a separate PR.

2022-11-10 18:13 UTC, Raildex commented on TombEngine/Game/items.cpp
> +		if (!item->Lua.CallbackOnKilledName.empty())
Should be part of [a5e602d](https://github.com/MontyTRC89/TombEngine/pull/828/commits/a5e602dc40d8f0f31b59e7c92176d2a6ec48dde1)

2022-11-10 18:14 UTC, Raildex commented on TombEngine/Game/items.h
> +struct EntityLuaData
Goes into [a5e602d](https://github.com/MontyTRC89/TombEngine/pull/828/commits/a5e602dc40d8f0f31b59e7c92176d2a6ec48dde1)

2022-11-10 18:14 UTC, Raildex commented on TombEngine/Game/items.h
> +	EntityLuaData Lua;
Goes into [a5e602d](https://github.com/MontyTRC89/TombEngine/pull/828/commits/a5e602dc40d8f0f31b59e7c92176d2a6ec48dde1)

2022-11-10 18:16 UTC, Raildex requested changes
Lua Changes should be in separate PR.

2022-11-10 19:50 UTC, Lwmte commented
> Lua Changes should be in separate PR.

Done

2022-11-11 06:13 UTC, Raildex approved these changes

2022-11-11 12:47 UTC, merged